--------------------------------------------------------
--  File created - Friday-October-30-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUCKET
--------------------------------------------------------

  CREATE TABLE "HR"."BUCKET" 
   (	"EMP_ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "HR"."EMPLOYEE" 
   (	"EMP_ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"HOURS_COMPLETED" NUMBER, 
	"HOURS_REMAINING" NUMBER, 
	"ELEVATION" NUMBER DEFAULT 0, 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	"COMMENTS" VARCHAR2(100 BYTE), 
	"MANAGER_ID" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TASK
--------------------------------------------------------

  CREATE TABLE "HR"."TASK" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"TASK_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"DATE_CREATED" DATE, 
	"DEADLINE" DATE, 
	"CONCERNS" VARCHAR2(250 BYTE), 
	"SKILL_SET_REQUIRED" VARCHAR2(100 BYTE), 
	"HOURS_NEEDED" NUMBER, 
	"PRIORITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKILL_SET
--------------------------------------------------------

  CREATE TABLE "HR"."SKILL_SET" 
   (	"EMP_ID" NUMBER, 
	"SKILL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.BUCKET
SET DEFINE OFF;
Insert into HR.BUCKET (EMP_ID,TASK_ID,STATUS) values (1001,101,'P');
Insert into HR.BUCKET (EMP_ID,TASK_ID,STATUS) values (1002,103,'C');
Insert into HR.BUCKET (EMP_ID,TASK_ID,STATUS) values (1856,107,'P');
Insert into HR.BUCKET (EMP_ID,TASK_ID,STATUS) values (1734,108,'R');
Insert into HR.BUCKET (EMP_ID,TASK_ID,STATUS) values (1442,110,'C');
Insert into HR.BUCKET (EMP_ID,TASK_ID,STATUS) values (1908,113,'P');
Insert into HR.BUCKET (EMP_ID,TASK_ID,STATUS) values (1357,115,'C');
Insert into HR.BUCKET (EMP_ID,TASK_ID,STATUS) values (1910,118,'P');
Insert into HR.BUCKET (EMP_ID,TASK_ID,STATUS) values (1449,121,'P');
Insert into HR.BUCKET (EMP_ID,TASK_ID,STATUS) values (1260,126,'F');
REM INSERTING into HR.EMPLOYEE
SET DEFINE OFF;
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1001,'Akash Philip',10,30,0,'akash','Employee',null,2001);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (2001,'Danishdeep Singh',26,14,0,'danish','Manager',null,0);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1002,'Himanshu Saxena',25,15,0,'himanshu','Employee',null,2001);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1856,'Malik Peck',24,16,0,'Marsden','Employee',null,2001);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1734,'Igor Pearson',30,10,0,'Cairo','Employee',null,2001);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1442,'Fitzgerald Mayo',27,13,0,'Chadwick','Employee',null,2001);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1148,'Nasim Avila',6,34,0,'Carter','Manager',null,0);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1908,'Bert Carroll',40,0,0,'Brady','Employee',null,1148);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1357,'Graham Leonard',36,4,0,'Ferris','Employee',null,1148);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1910,'Cairo Trevino',3,37,0,'Devin','Employee',null,2001);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1449,'Jelani Hardin',40,0,0,'Rashad','Employee',null,1148);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1260,'Beck Atkins',0,40,0,'Boris','Employee',null,1148);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1196,'Timon Holt',14,26,0,'Rooney','Employee',null,1493);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1754,'Mark Hampton',14,26,0,'Erasmus','Employee',null,2001);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1493,'Dylan Blanchard',13,27,0,'Brendan','Manager',null,0);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1736,'Herrod Benson',26,14,0,'Dieter','Employee',null,1493);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1388,'Salvador Gilbert',11,29,0,'Alexander','Employee',null,1266);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1933,'Benjamin Burgess',31,9,0,'Quamar','Employee',null,1493);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1570,'Brian Franklin',20,20,0,'Valentine','Employee',null,2001);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1406,'Nehru Wilkinson',14,26,0,'Myles','Employee',null,2001);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1872,'Nissim Haley',36,4,0,'Palmer','Employee',null,1266);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1266,'Calvin Colon',12,28,0,'Walker','Manager',null,0);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1540,'Emmanuel Meadows',29,11,0,'Boris','Employee',null,1266);
Insert into HR.EMPLOYEE (EMP_ID,NAME,HOURS_COMPLETED,HOURS_REMAINING,ELEVATION,PASSWORD,ROLE,COMMENTS,MANAGER_ID) values (1938,'Ahmed Merrill',27,13,0,'Carson','Employee',null,2001);
REM INSERTING into HR.TASK
SET DEFINE OFF;
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Write Web',101,'write Web',to_date('26-OCT-93','DD-MON-RR'),to_date('27-OCT-12','DD-MON-RR'),'philipakash@yahoo.com','HTML',120,3);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Designing',102,'Task assigned to employee',to_date('03-DEC-14','DD-MON-RR'),to_date('06-APR-16','DD-MON-RR'),'helpdesk@zepthy.com','CSS',2,3);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Bug Fixing',103,'Task assigned to employee',to_date('29-NOV-14','DD-MON-RR'),to_date('22-FEB-16','DD-MON-RR'),'helpdesk@zepthy.com','Teradata',1,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Database',104,'Task assigned to employee',to_date('27-DEC-14','DD-MON-RR'),to_date('14-OCT-16','DD-MON-RR'),'helpdesk@zepthy.com','DotNET',8,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Designing',105,'Task assigned to employee',to_date('13-NOV-14','DD-MON-RR'),to_date('02-AUG-16','DD-MON-RR'),'helpdesk@zepthy.com','Java',5,3);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Bug Fixing',106,'Task assigned to employee',to_date('20-MAY-15','DD-MON-RR'),to_date('09-DEC-15','DD-MON-RR'),'helpdesk@zepthy.com','DotNET',1,3);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Performance Analysis',107,'Task assigned to employee',to_date('12-APR-15','DD-MON-RR'),to_date('09-SEP-16','DD-MON-RR'),'helpdesk@zepthy.com','DotNET',2,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Database',108,'Task assigned to employee',to_date('13-FEB-15','DD-MON-RR'),to_date('22-FEB-16','DD-MON-RR'),'helpdesk@zepthy.com','DotNET',9,1);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Designing',109,'Task assigned to employee',to_date('08-OCT-15','DD-MON-RR'),to_date('27-JUN-16','DD-MON-RR'),'helpdesk@zepthy.com','C++',1,3);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Maintenance',110,'Task assigned to employee',to_date('06-JAN-15','DD-MON-RR'),to_date('05-JUN-16','DD-MON-RR'),'helpdesk@zepthy.com','HTML',9,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Automation',111,'Task assigned to employee',to_date('22-MAY-15','DD-MON-RR'),to_date('18-FEB-16','DD-MON-RR'),'helpdesk@zepthy.com','HTML',1,1);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Generate Reports',112,'Task assigned to employee',to_date('20-SEP-15','DD-MON-RR'),to_date('10-NOV-15','DD-MON-RR'),'helpdesk@zepthy.com','PHP',10,1);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Performance Analysis',113,'Task assigned to employee',to_date('16-DEC-14','DD-MON-RR'),to_date('16-JAN-16','DD-MON-RR'),'helpdesk@zepthy.com','Java',8,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Query',114,'Task assigned to employee',to_date('04-SEP-15','DD-MON-RR'),to_date('18-OCT-16','DD-MON-RR'),'helpdesk@zepthy.com','HTML',7,3);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Troubleshooting',115,'Task assigned to employee',to_date('03-DEC-14','DD-MON-RR'),to_date('01-AUG-16','DD-MON-RR'),'helpdesk@zepthy.com','HTML',3,3);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Designing',116,'Task assigned to employee',to_date('04-JAN-15','DD-MON-RR'),to_date('10-JUL-16','DD-MON-RR'),'helpdesk@zepthy.com','HTML',6,1);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Performance Analysis',117,'Task assigned to employee',to_date('12-APR-15','DD-MON-RR'),to_date('06-NOV-15','DD-MON-RR'),'helpdesk@zepthy.com','CSS',2,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Troubleshooting',118,'Task assigned to employee',to_date('04-DEC-14','DD-MON-RR'),to_date('13-OCT-16','DD-MON-RR'),'helpdesk@zepthy.com','Teradata',8,1);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Testing',119,'Task assigned to employee',to_date('09-MAR-15','DD-MON-RR'),to_date('03-OCT-16','DD-MON-RR'),'helpdesk@zepthy.com','HTML',8,1);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Database',120,'Task assigned to employee',to_date('13-MAY-15','DD-MON-RR'),to_date('19-JUL-16','DD-MON-RR'),'helpdesk@zepthy.com','Teradata',3,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Testing',121,'Task assigned to employee',to_date('16-NOV-14','DD-MON-RR'),to_date('16-JUN-16','DD-MON-RR'),'helpdesk@zepthy.com','C++',5,3);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Programming',122,'Task assigned to employee',to_date('17-MAY-15','DD-MON-RR'),to_date('05-APR-16','DD-MON-RR'),'helpdesk@zepthy.com','CSS',3,1);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Maintenance',123,'Task assigned to employee',to_date('31-MAY-15','DD-MON-RR'),to_date('27-MAR-16','DD-MON-RR'),'helpdesk@zepthy.com','C++',6,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Programming',124,'Task assigned to employee',to_date('01-MAR-15','DD-MON-RR'),to_date('15-JAN-16','DD-MON-RR'),'helpdesk@zepthy.com','PHP',9,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Automation',125,'Task assigned to employee',to_date('08-FEB-15','DD-MON-RR'),to_date('08-AUG-16','DD-MON-RR'),'helpdesk@zepthy.com','Java',3,3);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Bug Fixing',126,'Task assigned to employee',to_date('05-MAR-15','DD-MON-RR'),to_date('06-MAR-16','DD-MON-RR'),'helpdesk@zepthy.com','DotNET',3,1);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Query',127,'Task assigned to employee',to_date('22-OCT-15','DD-MON-RR'),to_date('12-SEP-16','DD-MON-RR'),'helpdesk@zepthy.com','HTML',5,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Designing',128,'Task assigned to employee',to_date('05-AUG-15','DD-MON-RR'),to_date('19-JUN-16','DD-MON-RR'),'helpdesk@zepthy.com','Java',9,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Generate Reports',129,'Task assigned to employee',to_date('22-NOV-14','DD-MON-RR'),to_date('01-OCT-16','DD-MON-RR'),'helpdesk@zepthy.com','Teradata',7,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Testing',130,'Task assigned to employee',to_date('12-FEB-15','DD-MON-RR'),to_date('03-MAY-16','DD-MON-RR'),'helpdesk@zepthy.com','HTML',6,2);
Insert into HR.TASK (NAME,TASK_ID,DESCRIPTION,DATE_CREATED,DEADLINE,CONCERNS,SKILL_SET_REQUIRED,HOURS_NEEDED,PRIORITY) values ('Query',131,'Task assigned to employee',to_date('07-AUG-15','DD-MON-RR'),to_date('14-NOV-15','DD-MON-RR'),'helpdesk@zepthy.com','Java',8,2);
REM INSERTING into HR.SKILL_SET
SET DEFINE OFF;
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1442,'CSS, DotNET');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1449,'Java, Teradata, PHP');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1754,'Teradata');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1002,'C++, DotNET');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1910,'Java, Teradata, C++');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1493,'Teradata');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1001,'C++');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1148,'CSS, Java, Teradata');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1872,'C++, Java, DotNET');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (2001,'C++, DotNET');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1266,'CSS');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1260,'PHP, C++');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1856,'C++, Java, DotNET');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1406,'Java, CSS, Teradata');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1570,'HTML, DotNET');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1908,'HTML, DotNET');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1933,'CSS, Java, Teradata');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1357,'Java, CSS, Teradata');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1736,'Teradata, HTML, CSS');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1734,'CSS');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1388,'CSS, DotNET');
Insert into HR.SKILL_SET (EMP_ID,SKILL) values (1196,'PHP, HTML, Teradata');
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."EMPLOYEE_PK" ON "HR"."EMPLOYEE" ("EMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TASK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TASK_PK" ON "HR"."TASK" ("TASK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "HR"."EMPLOYEE" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."EMPLOYEE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."EMPLOYEE" MODIFY ("HOURS_COMPLETED" NOT NULL ENABLE);
  ALTER TABLE "HR"."EMPLOYEE" MODIFY ("HOURS_REMAINING" NOT NULL ENABLE);
  ALTER TABLE "HR"."EMPLOYEE" MODIFY ("ELEVATION" NOT NULL ENABLE);
  ALTER TABLE "HR"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."EMPLOYEE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HR"."EMPLOYEE" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."EMPLOYEE" MODIFY ("MANAGER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "HR"."TASK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."TASK" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."TASK" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "HR"."TASK" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "HR"."TASK" MODIFY ("DEADLINE" NOT NULL ENABLE);
  ALTER TABLE "HR"."TASK" MODIFY ("CONCERNS" NOT NULL ENABLE);
  ALTER TABLE "HR"."TASK" MODIFY ("SKILL_SET_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "HR"."TASK" MODIFY ("HOURS_NEEDED" NOT NULL ENABLE);
  ALTER TABLE "HR"."TASK" MODIFY ("PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "HR"."TASK" ADD CONSTRAINT "TASK_PK" PRIMARY KEY ("TASK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
